<?php
$rows=$pdo->query("SELECT ss.*,u.unit_code,u.unit_name,u.current_meter,u.meter_type FROM service_schedules ss JOIN units u ON u.id=ss.unit_id ORDER BY FIELD(ss.status,'Terlambat','Jatuh Tempo','Akan Service','Terjadwal','Selesai'),ss.next_service_date")->fetchAll();
$units=$pdo->query('SELECT id,unit_code,unit_name,current_meter,meter_type FROM units ORDER BY unit_code')->fetchAll();
$mechanics=$pdo->query('SELECT id,name,employee_no FROM mechanics WHERE is_active=1 ORDER BY name')->fetchAll();
$wos=$pdo->query("SELECT m.*,u.unit_code,me.name mechanic_name FROM maintenance_orders m JOIN units u ON u.id=m.unit_id LEFT JOIN mechanics me ON me.id=m.mechanic_id ORDER BY m.id DESC LIMIT 100")->fetchAll();
$editWo=null;$histories=[];
if(!empty($_GET['edit_wo'])){$st=$pdo->prepare("SELECT m.*,u.unit_code,u.unit_name FROM maintenance_orders m JOIN units u ON u.id=m.unit_id WHERE m.id=?");$st->execute([(int)$_GET['edit_wo']]);$editWo=$st->fetch();if($editWo){$h=$pdo->prepare("SELECT sh.*,us.name changed_by_name FROM status_histories sh LEFT JOIN users us ON us.id=sh.changed_by WHERE sh.entity_type='maintenance_order' AND sh.entity_id=? ORDER BY sh.changed_at DESC");$h->execute([$editWo['id']]);$histories=$h->fetchAll();}}
?>
<?php if($m=flash('success')):?><div class="alert success"><?=e($m)?></div><?php endif;?><?php if($m=flash('error')):?><div class="alert error"><?=e($m)?></div><?php endif;?>
<?php if(can('service.edit')): ?><div class="card panel"><h3>Tambah / Perbarui Jadwal Service</h3><form class="form-grid compact" method="post" action="actions/save_service.php"><input type="hidden" name="_csrf" value="<?=csrf_token()?>"><label>Unit<select name="unit_id" required><?php foreach($units as $u):?><option value="<?=$u['id']?>"><?=e($u['unit_code'].' - '.$u['unit_name'])?></option><?php endforeach;?></select></label><label>Interval Service<input type="number" name="service_interval" value="250" required></label><label>Meter Service Berikut<input type="number" name="next_service_meter" required></label><label>Tanggal Rencana<input type="date" name="next_service_date" required></label><label>Catatan<input name="notes"></label><div><button class="btn primary">Simpan Jadwal</button></div></form></div><?php endif; ?>
<div class="card panel"><h3>Status Service Berkala</h3><table><thead><tr><th>Unit</th><th>Meter Aktual</th><th>Meter Berikut</th><th>Selisih</th><th>Tanggal</th><th>Status Otomatis</th><th>Catatan</th></tr></thead><tbody><?php foreach($rows as $r):$status=service_status((float)$r['current_meter'],(float)$r['next_service_meter'],$r['next_service_date']);?><tr><td><?=e($r['unit_code'])?></td><td><?=number_format($r['current_meter'],0,',','.')?> <?=e($r['meter_type'])?></td><td><?=number_format($r['next_service_meter'],0,',','.')?></td><td><?=number_format($r['next_service_meter']-$r['current_meter'],0,',','.')?></td><td><?=e($r['next_service_date'])?></td><td><span class="status <?=status_class($status)?>"><?=e($status)?></span></td><td><?=e($r['notes'])?></td></tr><?php endforeach;?></tbody></table></div>

<?php if(can('maintenance.edit')): ?>
<div class="card panel" id="form-work-order"><h3><?=$editWo?'Edit Work Order '.$editWo['work_order_no']:'Buat Work Order Lengkap'?></h3>
<form method="post" action="actions/<?=$editWo?'update_work_order.php':'save_work_order.php'?>" class="form-grid compact">
<input type="hidden" name="_csrf" value="<?=csrf_token()?>"><?php if($editWo):?><input type="hidden" name="id" value="<?=$editWo['id']?>"><?php endif;?>
<label>Unit<select name="unit_id" required <?=$editWo?'disabled':''?>><?php foreach($units as $u):?><option value="<?=$u['id']?>" <?=($editWo&&$editWo['unit_id']==$u['id'])?'selected':''?>><?=e($u['unit_code'].' - '.$u['unit_name'])?></option><?php endforeach;?></select></label>
<label>Jenis<select name="maintenance_type"><option <?=($editWo&&$editWo['maintenance_type']==='Periodic')?'selected':''?>>Periodic</option><option <?=($editWo&&$editWo['maintenance_type']==='Corrective')?'selected':''?>>Corrective</option><option <?=($editWo&&$editWo['maintenance_type']==='Inspection')?'selected':''?>>Inspection</option><option <?=($editWo&&$editWo['maintenance_type']==='Emergency')?'selected':''?>>Emergency</option></select></label>
<label>Prioritas<select name="priority" required><?php foreach(['Rendah','Sedang','Tinggi','Darurat'] as $p):?><option <?=($editWo&&$editWo['priority']===$p)?'selected':''?>><?=$p?></option><?php endforeach;?></select></label>
<label>Mekanik<select name="mechanic_id"><option value="">-- Belum ditentukan --</option><?php foreach($mechanics as $me):?><option value="<?=$me['id']?>" <?=($editWo&&$editWo['mechanic_id']==$me['id'])?'selected':''?>><?=e($me['name'].($me['employee_no']?' - '.$me['employee_no']:''))?></option><?php endforeach;?></select></label>
<label>Tanggal WO<input type="date" name="service_date" value="<?=e($editWo['service_date']??date('Y-m-d'))?>" required></label>
<label>Mulai Pekerjaan<input type="datetime-local" name="start_datetime" value="<?=!empty($editWo['start_datetime'])?date('Y-m-d\TH:i',strtotime($editWo['start_datetime'])):''?>"></label>
<label>Selesai Pekerjaan<input type="datetime-local" name="end_datetime" value="<?=!empty($editWo['end_datetime'])?date('Y-m-d\TH:i',strtotime($editWo['end_datetime'])):''?>"></label>
<label>Status<select name="status"><?php foreach(['Open','Dalam Proses','Menunggu Spare Part','Selesai','Dibatalkan'] as $s):?><option <?=($editWo&&$editWo['status']===$s)?'selected':''?>><?=$s?></option><?php endforeach;?></select></label>
<label>Meter Saat Service<input type="number" step="0.01" name="meter_at_service" value="<?=e((string)($editWo['meter_at_service']??''))?>"></label>
<label>Estimasi Durasi (jam)<input type="number" step="0.01" name="estimated_hours" value="<?=e((string)($editWo['estimated_hours']??''))?>"></label>
<label>Downtime Aktual (jam)<input type="number" step="0.01" name="downtime_hours" value="<?=e((string)($editWo['downtime_hours']??''))?>"></label>
<label>Biaya Aktual<input type="number" step="1" name="actual_cost" value="<?=e((string)($editWo['actual_cost']??''))?>"></label>
<label style="grid-column:span 2">Deskripsi Pekerjaan<input name="description" required value="<?=e($editWo['description']??'')?>"></label>
<label style="grid-column:span 2">Catatan Hasil Pekerjaan<textarea name="work_notes" rows="3"><?=e($editWo['work_notes']??'')?></textarea></label>
<?php if($editWo):?><label style="grid-column:span 2">Catatan Perubahan Status<input name="change_notes" placeholder="Contoh: pekerjaan dimulai / menunggu spare part"></label><?php endif;?>
<div><button class="btn primary"><?=$editWo?'Simpan Perubahan WO':'Buat Work Order'?></button><?php if($editWo):?> <a class="btn" href="<?=page_url('maintenance')?>">Batal</a><?php endif;?></div>
</form></div>
<?php endif; ?>

<div class="card panel"><h3>Daftar Work Order</h3><table><thead><tr><th>No WO</th><th>Unit</th><th>Tanggal</th><th>Jenis</th><th>Prioritas</th><th>Mekanik</th><th>Status</th><th>Downtime</th><th>Biaya</th><th>Aksi</th></tr></thead><tbody><?php foreach($wos as $w):?><tr><td><?=e($w['work_order_no'])?></td><td><?=e($w['unit_code'])?></td><td><?=e($w['service_date'])?></td><td><?=e($w['maintenance_type'])?></td><td><span class="status <?=in_array($w['priority'],['Tinggi','Darurat'],true)?'st-red':($w['priority']==='Sedang'?'st-orange':'st-green')?>"><?=e($w['priority']?:'Sedang')?></span></td><td><?=e($w['mechanic_name']?:'Belum ditentukan')?></td><td><span class="status <?=status_class($w['status'])?>"><?=e($w['status'])?></span></td><td><?=number_format((float)$w['downtime_hours'],1,',','.')?> jam</td><td><?=rupiah($w['actual_cost'])?></td><td><?php if(can('maintenance.edit')):?><a class="btn" href="<?=page_url('maintenance',['edit_wo'=>$w['id']])?>#form-work-order">Edit WO</a><?php else:?>-<?php endif;?></td></tr><?php endforeach;?></tbody></table></div>

<?php if($editWo):?><div class="card panel"><h3>Riwayat Status <?=$editWo['work_order_no']?></h3><table><thead><tr><th>Waktu</th><th>Status Lama</th><th>Status Baru</th><th>Catatan</th><th>Diubah Oleh</th></tr></thead><tbody><?php if(!$histories):?><tr><td colspan="5">Belum ada riwayat status.</td></tr><?php endif;?><?php foreach($histories as $h):?><tr><td><?=e($h['changed_at'])?></td><td><?=e($h['old_status']?:'-')?></td><td><span class="status <?=status_class($h['new_status'])?>"><?=e($h['new_status'])?></span></td><td><?=e($h['notes'])?></td><td><?=e($h['changed_by_name']?:'-')?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
