param(
    [string]$TargetDir = "C:\laragon\www\ServicePlan-BRA",
    [string]$DbName = "u646470441_ServicePlanBRA",
    [string]$DbUser = "root",
    [string]$DbPassword = ""
)

# ============================================================================
# ServicePlan-BRA: Synchronization & Local Laragon Hosting Script
# Multi-user compatible script with automatic root path & MySQL auto-detection
# Target Local Path: C:\laragon\www\ServicePlan-BRA
# Database Target: u646470441_ServicePlanBRA (Local MySQL Laragon)
# ============================================================================

# Auto-detect source directory (repository root directory containing this script)
$srcDir = (Get-Item $PSScriptRoot).Parent.FullName
$destDir = [System.IO.Path]::GetFullPath($TargetDir)
$laragonWebRoot = [System.IO.Path]::GetFullPath("C:\laragon\www")
$sqlPath = Join-Path $srcDir "scripts\u646470441_ServicePlanBRA.sql"

if (-not $destDir.StartsWith($laragonWebRoot.TrimEnd('\') + '\', [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "TargetDir harus berada di bawah C:\laragon\www dan tidak boleh menunjuk ke webroot langsung."
}

if ($DbName -notmatch '^[A-Za-z0-9_]+$' -or $DbUser -notmatch '^[A-Za-z0-9_]+$') {
    throw "DbName dan DbUser hanya boleh berisi huruf, angka, dan underscore."
}

if ($DbPassword -match '[\r\n"]') {
    throw 'DbPassword lokal tidak boleh mengandung newline atau tanda kutip ganda.'
}

# Auto-detect MySQL / MariaDB executable path
$mysqlExe = $null

$cmdMysql = Get-Command mysql -ErrorAction SilentlyContinue
if ($cmdMysql) {
    $mysqlExe = $cmdMysql.Source
} else {
    $possiblePaths = @(
        Get-ChildItem -Path "C:\laragon\bin\mysql" -Filter "mysql.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName
        Get-ChildItem -Path "C:\laragon\bin\mariadb" -Filter "mysql.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName
    )
    if ($possiblePaths.Count -gt 0) {
        $mysqlExe = $possiblePaths[0]
    }
}

Write-Host "============================================================================" -ForegroundColor Cyan
Write-Host " ServicePlan-BRA Local Laragon Sync Utility" -ForegroundColor Cyan
Write-Host " Source: $srcDir" -ForegroundColor Gray
Write-Host " Target: $destDir" -ForegroundColor Gray
Write-Host "============================================================================" -ForegroundColor Cyan

# 1. Ensure target directory exists
if (-not (Test-Path $destDir)) {
    New-Item -Path $destDir -ItemType Directory -Force | Out-Null
}

Write-Host "`n[1/4] Synchronizing files to Laragon webroot ($destDir)..." -ForegroundColor Cyan
robocopy $srcDir $destDir /MIR /XD .git .gemini .agents .codex .runtime brain scratch /XF .env *.sql /R:2 /W:1 | Out-Null
$robocopyExitCode = $LASTEXITCODE
if ($robocopyExitCode -gt 7) {
    throw "Robocopy gagal dengan exit code $robocopyExitCode."
}
Write-Host "Files synchronized successfully!" -ForegroundColor Green

# Add local-only Apache environment configuration to the mirrored copy. This
# block never modifies the repository .htaccess and is recreated on each sync.
$sessionDir = "C:\laragon\tmp\ServicePlan-BRA-sessions"
New-Item -Path $sessionDir -ItemType Directory -Force | Out-Null
$targetHtaccess = Join-Path $destDir '.htaccess'
$apacheSessionDir = $sessionDir.Replace('\', '/')
$localEnvironmentBlock = @"

# BEGIN LARAGON LOCAL ENVIRONMENT - generated by sync_to_laragon.ps1
<IfModule mod_env.c>
    SetEnv APP_ENV "local"
    SetEnv APP_ORIGIN "http://localhost"
    SetEnv APP_ALLOWED_ORIGINS "http://localhost,http://127.0.0.1,http://serviceplan-bra.test"
    SetEnv DB_HOST "127.0.0.1"
    SetEnv DB_PORT "3306"
    SetEnv DB_NAME "$DbName"
    SetEnv DB_USER "$DbUser"
    SetEnv DB_PASSWORD "$DbPassword"
    SetEnv SESSION_NAME "BRASESSID_LOCAL"
    SetEnv SESSION_SAVE_PATH "$apacheSessionDir"
</IfModule>
# END LARAGON LOCAL ENVIRONMENT
"@
Add-Content -LiteralPath $targetHtaccess -Value $localEnvironmentBlock -Encoding UTF8

# 2. Prepare MySQL database
Write-Host "`n[2/4] Verifying & preparing MySQL database '$DbName'..." -ForegroundColor Cyan
if ($mysqlExe -and (Test-Path $mysqlExe)) {
    Write-Host "Found MySQL executable: $mysqlExe" -ForegroundColor Gray

    $mysqlArgs = @('-u', $DbUser)
    if ($DbPassword) {
        $mysqlArgs += "-p$DbPassword"
    }
    
    # Create DB (Do not drop, preserve data like archived items)
    $createDbCmd = "CREATE DATABASE IF NOT EXISTS ``$DbName`` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
    & $mysqlExe @mysqlArgs -e $createDbCmd
    if ($LASTEXITCODE -ne 0) {
        throw "Gagal membuat atau mengakses database '$DbName'."
    }
    
    if (Test-Path $sqlPath) {
        Write-Host "`n[3/4] Importing SQL schema & data into local MySQL..." -ForegroundColor Cyan
        $mysqlSourcePath = $sqlPath.Replace('\', '/')
        & $mysqlExe @mysqlArgs --default-character-set=utf8mb4 $DbName -e "source $mysqlSourcePath"
        if ($LASTEXITCODE -ne 0) {
            throw "Import SQL ke database '$DbName' gagal."
        }
        Write-Host "Database '$DbName' successfully synced to local MySQL!" -ForegroundColor Green

        $passwordResetScript = Join-Path $srcDir 'scripts\set_local_temporary_passwords.php'
        $phpExe = Get-ChildItem -Path 'C:\laragon\bin\php' -Filter 'php.exe' -Recurse -ErrorAction SilentlyContinue |
            Sort-Object FullName -Descending |
            Select-Object -First 1 -ExpandProperty FullName
        if ($phpExe -and (Test-Path $passwordResetScript)) {
            Write-Host "`n[4/4] Applying local-only temporary passwords..." -ForegroundColor Cyan
            $previousEnvironment = @{
                APP_ENV = $env:APP_ENV
                DB_HOST = $env:DB_HOST
                DB_PORT = $env:DB_PORT
                DB_NAME = $env:DB_NAME
                DB_USER = $env:DB_USER
                DB_PASSWORD = $env:DB_PASSWORD
            }
            try {
                $env:APP_ENV = 'local'
                $env:DB_HOST = '127.0.0.1'
                $env:DB_PORT = '3306'
                $env:DB_NAME = $DbName
                $env:DB_USER = $DbUser
                $env:DB_PASSWORD = $DbPassword
                & $phpExe $passwordResetScript --confirm-local-reset
                if ($LASTEXITCODE -ne 0) {
                    throw 'Reset password sementara lokal gagal.'
                }
            } finally {
                $env:APP_ENV = $previousEnvironment.APP_ENV
                $env:DB_HOST = $previousEnvironment.DB_HOST
                $env:DB_PORT = $previousEnvironment.DB_PORT
                $env:DB_NAME = $previousEnvironment.DB_NAME
                $env:DB_USER = $previousEnvironment.DB_USER
                $env:DB_PASSWORD = $previousEnvironment.DB_PASSWORD
            }
        } else {
            Write-Host '[!] PHP atau script reset password tidak ditemukan; password dump tidak diubah.' -ForegroundColor Yellow
        }
    } else {
        Write-Host "[!] SQL file not found at: $sqlPath" -ForegroundColor Yellow
    }
} else {
    Write-Host "[!] MySQL executable not found. Make sure Laragon MySQL service is installed/running." -ForegroundColor Yellow
    Write-Host "Skipping database import step. Code files were still copied to webroot." -ForegroundColor Yellow
}

Write-Host "`n============================================================================" -ForegroundColor Green
Write-Host "Synchronization finished!" -ForegroundColor Green
Write-Host "Access local hosting at: http://localhost/$(Split-Path $destDir -Leaf)/index.html" -ForegroundColor Green
Write-Host "============================================================================" -ForegroundColor Green

